"""DISCOVER framework data models.

Implements the core data structures:
  - CalendarEvent / SchedulingScenario: the task environment
  - Evidence / ValueHypothesis / ValueEvidenceLedger: the inferential machinery
  - BehavioralSignal / ConversationalSignal: logged signals for post-hoc decomposition
  - Round / Session: experimental session management
"""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────

class Phase(str, Enum):
    EXPLORATION = "exploration"    # Rounds 1-5:  broad scenarios
    PROBING = "probing"            # Rounds 6-10: targeted probing
    STRESS_TEST = "stress_test"    # Rounds 11-15: forced trade-offs


class RoundStatus(str, Enum):
    PENDING = "pending"
    SCENARIO_PRESENTED = "scenario_presented"
    IN_PROGRESS = "in_progress"
    AWAITING_REFLECTION = "awaiting_reflection"
    COMPLETED = "completed"


class EventAction(str, Enum):
    ACCEPT = "accept"
    DECLINE = "decline"
    RESCHEDULE = "reschedule"
    MODIFY = "modify"
    PRIORITIZE = "prioritize"


class AbstractionLevel(str, Enum):
    RAW_ACTION = "raw_action"
    BEHAVIORAL_PATTERN = "behavioral_pattern"
    SCHEDULING_PRIORITY = "scheduling_priority"
    ABSTRACT_VALUE = "abstract_value"


# ── Calendar & Scenarios ─────────────────────────────────────────────

class CalendarEvent(BaseModel):
    """A single event on the participant's calendar."""
    id: str = Field(default_factory=lambda: f"evt_{uuid.uuid4().hex[:8]}")
    title: str
    day_index: int               # 0=Mon .. 4=Fri
    start: str                   # "HH:MM"
    end: str                     # "HH:MM"
    tone: str = "blue"           # UI color class
    category: str = "work"       # work | personal | health | social | obligation
    description: str = ""
    source: str = "system"       # system | user | conflict_architect
    is_movable: bool = True
    is_new: bool = False         # True for newly injected events this round
    metadata: dict[str, Any] = Field(default_factory=dict)


class EmailMessage(BaseModel):
    """A simulated email that presents a scheduling request or conflict."""
    id: str = Field(default_factory=lambda: f"email_{uuid.uuid4().hex[:8]}")
    sender: str
    subject: str
    body: str
    requires_scheduling: bool = True
    proposed_event: CalendarEvent | None = None
    value_tensions: list[str] = Field(default_factory=list)
    round_num: int = 0


class SchedulingScenario(BaseModel):
    """A complete round scenario generated by the Conflict Architect."""
    round_num: int
    phase: Phase
    emails: list[EmailMessage] = Field(default_factory=list)
    injected_events: list[CalendarEvent] = Field(default_factory=list)
    intended_tensions: list[str] = Field(default_factory=list)
    difficulty: str = "moderate"  # easy | moderate | hard
    targeting_rationale: str = ""  # Why this scenario was chosen


# ── Behavioral & Conversational Signals ──────────────────────────────

class BehavioralSignal(BaseModel):
    """A logged behavioral action from the scheduling task."""
    id: str = Field(default_factory=lambda: f"sig_{uuid.uuid4().hex[:8]}")
    timestamp: float = Field(default_factory=time.time)
    round_num: int
    action: EventAction
    event_id: str
    event_title: str = ""
    details: dict[str, Any] = Field(default_factory=dict)
    # e.g., {"original_time": "09:00", "new_time": "17:00", "reason": "moved to evening"}


class ConversationalSignal(BaseModel):
    """A logged conversational exchange."""
    id: str = Field(default_factory=lambda: f"conv_{uuid.uuid4().hex[:8]}")
    timestamp: float = Field(default_factory=time.time)
    round_num: int
    role: str                    # "user" | "assistant"
    content: str
    signal_type: str = "chat"    # chat | reflection | rationale


# ── Value Evidence Ledger ────────────────────────────────────────────

class Evidence(BaseModel):
    """A single piece of evidence supporting or challenging a value hypothesis."""
    id: str = Field(default_factory=lambda: f"evi_{uuid.uuid4().hex[:8]}")
    round_num: int
    abstraction_level: AbstractionLevel
    description: str             # What the user did/said
    source_type: str             # "behavioral" | "conversational"
    source_id: str               # Reference to BehavioralSignal or ConversationalSignal
    supports: bool = True        # True = supporting, False = disconfirming
    strength: float = 0.5        # 0.0-1.0


class ValueHypothesis(BaseModel):
    """A hypothesis about a value the participant holds."""
    id: str = Field(default_factory=lambda: f"val_{uuid.uuid4().hex[:8]}")
    label: str                   # e.g., "Work-life boundaries"
    description: str             # Fuller description
    confidence: float = 0.5      # 0.0-1.0
    evidence_ids: list[str] = Field(default_factory=list)
    first_observed_round: int = 1
    last_updated_round: int = 1
    abstraction_ladder: dict[str, str] = Field(default_factory=dict)
    # e.g., {"raw_action": "declined 7pm meeting",
    #        "behavioral_pattern": "protects evenings consistently",
    #        "scheduling_priority": "personal time > work overflow",
    #        "abstract_value": "work-life boundaries"}


class ValueEvidenceLedger(BaseModel):
    """The complete ledger of value hypotheses and their evidence."""
    hypotheses: list[ValueHypothesis] = Field(default_factory=list)
    evidence: list[Evidence] = Field(default_factory=list)

    def get_hypothesis(self, hypothesis_id: str) -> ValueHypothesis | None:
        return next((h for h in self.hypotheses if h.id == hypothesis_id), None)

    def get_evidence_for(self, hypothesis_id: str) -> list[Evidence]:
        hyp = self.get_hypothesis(hypothesis_id)
        if not hyp:
            return []
        return [e for e in self.evidence if e.id in hyp.evidence_ids]

    def to_summary(self) -> list[dict]:
        """Return a simplified summary for agent prompts."""
        result = []
        for h in self.hypotheses:
            supporting = [e for e in self.evidence if e.id in h.evidence_ids and e.supports]
            challenging = [e for e in self.evidence if e.id in h.evidence_ids and not e.supports]
            result.append({
                "value": h.label,
                "description": h.description,
                "confidence": h.confidence,
                "supporting_evidence_count": len(supporting),
                "challenging_evidence_count": len(challenging),
                "ladder": h.abstraction_ladder,
                "first_seen": h.first_observed_round,
                "last_updated": h.last_updated_round,
            })
        return result

    def to_weights(self) -> list[dict]:
        """Return value weights for the frontend ValuesPanel."""
        tones = ["green", "rose", "amber", "cyan", "violet",
                 "blue", "orange", "teal", "pink", "indigo"]
        sorted_hyps = sorted(self.hypotheses, key=lambda h: h.confidence, reverse=True)
        total_conf = sum(h.confidence for h in sorted_hyps) or 1.0
        return [
            {
                "label": h.label,
                "weight": round((h.confidence / total_conf) * 100),
                "tone": tones[i % len(tones)],
            }
            for i, h in enumerate(sorted_hyps[:10])
        ]


# ── Debate Records ───────────────────────────────────────────────────

class DebateRecord(BaseModel):
    """Record of an Advocate-Challenger-Synthesizer deliberation cycle."""
    round_num: int
    advocate_argument: str = ""
    challenger_argument: str = ""
    synthesis: str = ""
    updated_hypotheses: list[str] = Field(default_factory=list)  # hypothesis IDs modified
    new_hypotheses: list[str] = Field(default_factory=list)      # hypothesis IDs created
    timestamp: float = Field(default_factory=time.time)


# ── Round & Session ──────────────────────────────────────────────────

class Round(BaseModel):
    """A single round within the experimental session."""
    round_num: int
    phase: Phase
    status: RoundStatus = RoundStatus.PENDING
    scenario: SchedulingScenario | None = None
    behavioral_signals: list[BehavioralSignal] = Field(default_factory=list)
    conversational_signals: list[ConversationalSignal] = Field(default_factory=list)
    debate_record: DebateRecord | None = None
    reflection_prompt: str | None = None
    reflection_response: str | None = None
    is_reflection_round: bool = False


class Session(BaseModel):
    """A complete experimental session for one participant."""
    id: str = Field(default_factory=lambda: f"sess_{uuid.uuid4().hex[:8]}")
    participant_id: str = ""
    created_at: float = Field(default_factory=time.time)
    current_round: int = 0       # 0 = not started
    rounds: list[Round] = Field(default_factory=list)
    calendar_events: list[CalendarEvent] = Field(default_factory=list)
    value_ledger: ValueEvidenceLedger = Field(default_factory=ValueEvidenceLedger)
    debate_history: list[DebateRecord] = Field(default_factory=list)
    chat_history: list[dict] = Field(default_factory=list)  # Full chat for context
    pre_study_values: list[str] = Field(default_factory=list)   # For NVDR
    post_study_values: list[str] = Field(default_factory=list)  # For NVDR

    def get_phase(self, round_num: int | None = None) -> Phase:
        r = round_num or self.current_round
        if r <= 5:
            return Phase.EXPLORATION
        elif r <= 10:
            return Phase.PROBING
        else:
            return Phase.STRESS_TEST

    def current_round_obj(self) -> Round | None:
        return next((r for r in self.rounds if r.round_num == self.current_round), None)

    def get_all_behavioral_signals(self) -> list[BehavioralSignal]:
        signals = []
        for r in self.rounds:
            signals.extend(r.behavioral_signals)
        return signals

    def get_all_conversational_signals(self) -> list[ConversationalSignal]:
        signals = []
        for r in self.rounds:
            signals.extend(r.conversational_signals)
        return signals
